spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fxDeals
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  server:
    port: 8080
  logging:
    level:
      org.springframework.data.jpa.repository.query: debug
      org.hibernate.SQL: debug